//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrobaGym
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calentamiento
    {
        public int Num_registro { get; set; }
        public Nullable<System.DateTime> FechaYHora { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string EmpleadoDeTurno { get; set; }
    
        public virtual Personal Personal { get; set; }
    }
}
