//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrobaGym
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public Personal()
        {
            this.Calentamientos = new HashSet<Calentamiento>();
            this.Registro_Productos = new HashSet<Registro_Productos>();
            this.Seguimientoes = new HashSet<Seguimiento>();
        }
    
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Usuario { get; set; }
        public string Contraseña { get; set; }
        public Nullable<decimal> Salario { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public string Horario { get; set; }
        public Nullable<System.DateTime> Fecha_Contratacion { get; set; }
        public byte[] Foto { get; set; }
        public string Tipo { get; set; }
    
        public virtual ICollection<Calentamiento> Calentamientos { get; set; }
        public virtual ICollection<Registro_Productos> Registro_Productos { get; set; }
        public virtual ICollection<Seguimiento> Seguimientoes { get; set; }
    }
}
