//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrobaGym
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Registro_Productos = new HashSet<Registro_Productos>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Precio { get; set; }
    
        public virtual ICollection<Registro_Productos> Registro_Productos { get; set; }
    }
}
