//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrobaGym
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programa
    {
        public Programa()
        {
            this.Clientes = new HashSet<Cliente>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Precio_Inscripcion { get; set; }
        public Nullable<decimal> Precio_periodo { get; set; }
    
        public virtual ICollection<Cliente> Clientes { get; set; }
    }
}
