//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrobaGym
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro_Productos
    {
        public int IdRegistro { get; set; }
        public Nullable<int> Id_Producto { get; set; }
        public Nullable<int> Cantidad_Vendida { get; set; }
        public Nullable<System.DateTime> FechaYHora { get; set; }
        public string Empleado_Turno { get; set; }
    
        public virtual Personal Personal { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
