//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrobaGym
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguimiento
    {
        public int Id_registro { get; set; }
        public string Id_Cliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Peso { get; set; }
        public Nullable<int> Caja_Toracica { get; set; }
        public Nullable<int> Cintura { get; set; }
        public Nullable<int> Abdomen { get; set; }
        public Nullable<int> Cadera { get; set; }
        public Nullable<int> Muslo { get; set; }
        public Nullable<int> Gastronomio { get; set; }
        public Nullable<int> Biceps { get; set; }
        public Nullable<int> Flexibilidad { get; set; }
        public Nullable<decimal> Saldo_Mes { get; set; }
        public string Empleado_turno { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Personal Personal { get; set; }
    }
}
