#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrobaGym.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AtGym")]
	public partial class AtGymLINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertCliente_Programa(Cliente_Programa instance);
    partial void UpdateCliente_Programa(Cliente_Programa instance);
    partial void DeleteCliente_Programa(Cliente_Programa instance);
    partial void InsertPersonal(Personal instance);
    partial void UpdatePersonal(Personal instance);
    partial void DeletePersonal(Personal instance);
    partial void InsertProductos(Productos instance);
    partial void UpdateProductos(Productos instance);
    partial void DeleteProductos(Productos instance);
    partial void InsertProgramas(Programas instance);
    partial void UpdateProgramas(Programas instance);
    partial void DeleteProgramas(Programas instance);
    partial void InsertRegistro_Productos(Registro_Productos instance);
    partial void UpdateRegistro_Productos(Registro_Productos instance);
    partial void DeleteRegistro_Productos(Registro_Productos instance);
    partial void InsertSeguimiento(Seguimiento instance);
    partial void UpdateSeguimiento(Seguimiento instance);
    partial void DeleteSeguimiento(Seguimiento instance);
    partial void InsertCalentamientos(Calentamientos instance);
    partial void UpdateCalentamientos(Calentamientos instance);
    partial void DeleteCalentamientos(Calentamientos instance);
    partial void InsertGastos(Gastos instance);
    partial void UpdateGastos(Gastos instance);
    partial void DeleteGastos(Gastos instance);
    #endregion
		
		public AtGymLINQDataContext() : 
				base(global::ArrobaGym.Properties.Settings.Default.AtGymConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public AtGymLINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AtGymLINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AtGymLINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AtGymLINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cliente> Cliente
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Cliente_Programa> Cliente_Programa
		{
			get
			{
				return this.GetTable<Cliente_Programa>();
			}
		}
		
		public System.Data.Linq.Table<Personal> Personal
		{
			get
			{
				return this.GetTable<Personal>();
			}
		}
		
		public System.Data.Linq.Table<Productos> Productos
		{
			get
			{
				return this.GetTable<Productos>();
			}
		}
		
		public System.Data.Linq.Table<Programas> Programas
		{
			get
			{
				return this.GetTable<Programas>();
			}
		}
		
		public System.Data.Linq.Table<Registro_Productos> Registro_Productos
		{
			get
			{
				return this.GetTable<Registro_Productos>();
			}
		}
		
		public System.Data.Linq.Table<Seguimiento> Seguimiento
		{
			get
			{
				return this.GetTable<Seguimiento>();
			}
		}
		
		public System.Data.Linq.Table<Calentamientos> Calentamientos
		{
			get
			{
				return this.GetTable<Calentamientos>();
			}
		}
		
		public System.Data.Linq.Table<Gastos> Gastos
		{
			get
			{
				return this.GetTable<Gastos>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Codigo;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Telefono;
		
		private string _Direccion;
		
		private string _Factores_de_riesgos;
		
		private string _Objetivos;
		
		private System.Data.Linq.Binary _Imagen;
		
		private System.DateTime _Fecha_Inscripcion;
		
		private string _Status;
		
		private System.Nullable<decimal> _Saldo;
		
		private System.Nullable<System.DateTime> _Ultimo_Pago;
		
		private System.Nullable<int> _IdPrograma;
		
		private EntitySet<Cliente_Programa> _Cliente_Programa;
		
		private EntitySet<Seguimiento> _Seguimiento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCodigoChanging(string value);
    partial void OnCodigoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnFactores_de_riesgosChanging(string value);
    partial void OnFactores_de_riesgosChanged();
    partial void OnObjetivosChanging(string value);
    partial void OnObjetivosChanged();
    partial void OnImagenChanging(System.Data.Linq.Binary value);
    partial void OnImagenChanged();
    partial void OnFecha_InscripcionChanging(System.DateTime value);
    partial void OnFecha_InscripcionChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnSaldoChanging(System.Nullable<decimal> value);
    partial void OnSaldoChanged();
    partial void OnUltimo_PagoChanging(System.Nullable<System.DateTime> value);
    partial void OnUltimo_PagoChanged();
    partial void OnIdProgramaChanging(System.Nullable<int> value);
    partial void OnIdProgramaChanged();
    #endregion
		
		public Cliente()
		{
			this._Cliente_Programa = new EntitySet<Cliente_Programa>(new Action<Cliente_Programa>(this.attach_Cliente_Programa), new Action<Cliente_Programa>(this.detach_Cliente_Programa));
			this._Seguimiento = new EntitySet<Seguimiento>(new Action<Seguimiento>(this.attach_Seguimiento), new Action<Seguimiento>(this.detach_Seguimiento));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="NChar(6) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(15)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(100)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Factores_de_riesgos", DbType="VarChar(300)")]
		public string Factores_de_riesgos
		{
			get
			{
				return this._Factores_de_riesgos;
			}
			set
			{
				if ((this._Factores_de_riesgos != value))
				{
					this.OnFactores_de_riesgosChanging(value);
					this.SendPropertyChanging();
					this._Factores_de_riesgos = value;
					this.SendPropertyChanged("Factores_de_riesgos");
					this.OnFactores_de_riesgosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Objetivos", DbType="VarChar(100)")]
		public string Objetivos
		{
			get
			{
				return this._Objetivos;
			}
			set
			{
				if ((this._Objetivos != value))
				{
					this.OnObjetivosChanging(value);
					this.SendPropertyChanging();
					this._Objetivos = value;
					this.SendPropertyChanged("Objetivos");
					this.OnObjetivosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Imagen
		{
			get
			{
				return this._Imagen;
			}
			set
			{
				if ((this._Imagen != value))
				{
					this.OnImagenChanging(value);
					this.SendPropertyChanging();
					this._Imagen = value;
					this.SendPropertyChanged("Imagen");
					this.OnImagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Inscripcion", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Inscripcion
		{
			get
			{
				return this._Fecha_Inscripcion;
			}
			set
			{
				if ((this._Fecha_Inscripcion != value))
				{
					this.OnFecha_InscripcionChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Inscripcion = value;
					this.SendPropertyChanged("Fecha_Inscripcion");
					this.OnFecha_InscripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saldo", DbType="Money")]
		public System.Nullable<decimal> Saldo
		{
			get
			{
				return this._Saldo;
			}
			set
			{
				if ((this._Saldo != value))
				{
					this.OnSaldoChanging(value);
					this.SendPropertyChanging();
					this._Saldo = value;
					this.SendPropertyChanged("Saldo");
					this.OnSaldoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ultimo_Pago", DbType="Date")]
		public System.Nullable<System.DateTime> Ultimo_Pago
		{
			get
			{
				return this._Ultimo_Pago;
			}
			set
			{
				if ((this._Ultimo_Pago != value))
				{
					this.OnUltimo_PagoChanging(value);
					this.SendPropertyChanging();
					this._Ultimo_Pago = value;
					this.SendPropertyChanged("Ultimo_Pago");
					this.OnUltimo_PagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPrograma", DbType="Int")]
		public System.Nullable<int> IdPrograma
		{
			get
			{
				return this._IdPrograma;
			}
			set
			{
				if ((this._IdPrograma != value))
				{
					this.OnIdProgramaChanging(value);
					this.SendPropertyChanging();
					this._IdPrograma = value;
					this.SendPropertyChanged("IdPrograma");
					this.OnIdProgramaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Cliente_Programa", Storage="_Cliente_Programa", ThisKey="Id", OtherKey="ID_Cliente")]
		public EntitySet<Cliente_Programa> Cliente_Programa
		{
			get
			{
				return this._Cliente_Programa;
			}
			set
			{
				this._Cliente_Programa.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Seguimiento", Storage="_Seguimiento", ThisKey="Id", OtherKey="Cliente_ID")]
		public EntitySet<Seguimiento> Seguimiento
		{
			get
			{
				return this._Seguimiento;
			}
			set
			{
				this._Seguimiento.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cliente_Programa(Cliente_Programa entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Cliente_Programa(Cliente_Programa entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
		
		private void attach_Seguimiento(Seguimiento entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Seguimiento(Seguimiento entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente_Programa")]
	public partial class Cliente_Programa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Cliente;
		
		private int _ID_Programa;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Programas> _Programas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ClienteChanging(int value);
    partial void OnID_ClienteChanged();
    partial void OnID_ProgramaChanging(int value);
    partial void OnID_ProgramaChanged();
    #endregion
		
		public Cliente_Programa()
		{
			this._Cliente = default(EntityRef<Cliente>);
			this._Programas = default(EntityRef<Programas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Cliente", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Cliente
		{
			get
			{
				return this._ID_Cliente;
			}
			set
			{
				if ((this._ID_Cliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ClienteChanging(value);
					this.SendPropertyChanging();
					this._ID_Cliente = value;
					this.SendPropertyChanged("ID_Cliente");
					this.OnID_ClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Programa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Programa
		{
			get
			{
				return this._ID_Programa;
			}
			set
			{
				if ((this._ID_Programa != value))
				{
					if (this._Programas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ProgramaChanging(value);
					this.SendPropertyChanging();
					this._ID_Programa = value;
					this.SendPropertyChanged("ID_Programa");
					this.OnID_ProgramaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Cliente_Programa", Storage="_Cliente", ThisKey="ID_Cliente", OtherKey="Id", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Cliente_Programa.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Cliente_Programa.Add(this);
						this._ID_Cliente = value.Id;
					}
					else
					{
						this._ID_Cliente = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Programas_Cliente_Programa", Storage="_Programas", ThisKey="ID_Programa", OtherKey="Id", IsForeignKey=true)]
		public Programas Programas
		{
			get
			{
				return this._Programas.Entity;
			}
			set
			{
				Programas previousValue = this._Programas.Entity;
				if (((previousValue != value) 
							|| (this._Programas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Programas.Entity = null;
						previousValue.Cliente_Programa.Remove(this);
					}
					this._Programas.Entity = value;
					if ((value != null))
					{
						value.Cliente_Programa.Add(this);
						this._ID_Programa = value.Id;
					}
					else
					{
						this._ID_Programa = default(int);
					}
					this.SendPropertyChanged("Programas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Personal")]
	public partial class Personal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Cedula;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Usuario;
		
		private string _Contraseña;
		
		private System.Nullable<decimal> _Salario;
		
		private string _Telefono;
		
		private string _Direccion;
		
		private string _Correo;
		
		private string _Horario;
		
		private System.Nullable<System.DateTime> _Fecha_Contratacion;
		
		private System.Data.Linq.Binary _Foto;
		
		private string _Tipo;
		
		private EntitySet<Registro_Productos> _Registro_Productos;
		
		private EntitySet<Seguimiento> _Seguimiento;
		
		private EntitySet<Calentamientos> _Calentamientos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCedulaChanging(string value);
    partial void OnCedulaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnContraseñaChanging(string value);
    partial void OnContraseñaChanged();
    partial void OnSalarioChanging(System.Nullable<decimal> value);
    partial void OnSalarioChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnHorarioChanging(string value);
    partial void OnHorarioChanged();
    partial void OnFecha_ContratacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_ContratacionChanged();
    partial void OnFotoChanging(System.Data.Linq.Binary value);
    partial void OnFotoChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    #endregion
		
		public Personal()
		{
			this._Registro_Productos = new EntitySet<Registro_Productos>(new Action<Registro_Productos>(this.attach_Registro_Productos), new Action<Registro_Productos>(this.detach_Registro_Productos));
			this._Seguimiento = new EntitySet<Seguimiento>(new Action<Seguimiento>(this.attach_Seguimiento), new Action<Seguimiento>(this.detach_Seguimiento));
			this._Calentamientos = new EntitySet<Calentamientos>(new Action<Calentamientos>(this.attach_Calentamientos), new Action<Calentamientos>(this.detach_Calentamientos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="NChar(11) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this.OnCedulaChanging(value);
					this.SendPropertyChanging();
					this._Cedula = value;
					this.SendPropertyChanged("Cedula");
					this.OnCedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(50)")]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salario", DbType="Money")]
		public System.Nullable<decimal> Salario
		{
			get
			{
				return this._Salario;
			}
			set
			{
				if ((this._Salario != value))
				{
					this.OnSalarioChanging(value);
					this.SendPropertyChanging();
					this._Salario = value;
					this.SendPropertyChanged("Salario");
					this.OnSalarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(15)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(100)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(50)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Horario", DbType="VarChar(100)")]
		public string Horario
		{
			get
			{
				return this._Horario;
			}
			set
			{
				if ((this._Horario != value))
				{
					this.OnHorarioChanging(value);
					this.SendPropertyChanging();
					this._Horario = value;
					this.SendPropertyChanged("Horario");
					this.OnHorarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Contratacion", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha_Contratacion
		{
			get
			{
				return this._Fecha_Contratacion;
			}
			set
			{
				if ((this._Fecha_Contratacion != value))
				{
					this.OnFecha_ContratacionChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Contratacion = value;
					this.SendPropertyChanged("Fecha_Contratacion");
					this.OnFecha_ContratacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				if ((this._Foto != value))
				{
					this.OnFotoChanging(value);
					this.SendPropertyChanging();
					this._Foto = value;
					this.SendPropertyChanged("Foto");
					this.OnFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(50)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personal_Registro_Productos", Storage="_Registro_Productos", ThisKey="Id", OtherKey="Empleado_Turno")]
		public EntitySet<Registro_Productos> Registro_Productos
		{
			get
			{
				return this._Registro_Productos;
			}
			set
			{
				this._Registro_Productos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personal_Seguimiento", Storage="_Seguimiento", ThisKey="Id", OtherKey="Personal_ID")]
		public EntitySet<Seguimiento> Seguimiento
		{
			get
			{
				return this._Seguimiento;
			}
			set
			{
				this._Seguimiento.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personal_Calentamientos", Storage="_Calentamientos", ThisKey="Id", OtherKey="EmpleadoDeTurno")]
		public EntitySet<Calentamientos> Calentamientos
		{
			get
			{
				return this._Calentamientos;
			}
			set
			{
				this._Calentamientos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Registro_Productos(Registro_Productos entity)
		{
			this.SendPropertyChanging();
			entity.Personal = this;
		}
		
		private void detach_Registro_Productos(Registro_Productos entity)
		{
			this.SendPropertyChanging();
			entity.Personal = null;
		}
		
		private void attach_Seguimiento(Seguimiento entity)
		{
			this.SendPropertyChanging();
			entity.Personal = this;
		}
		
		private void detach_Seguimiento(Seguimiento entity)
		{
			this.SendPropertyChanging();
			entity.Personal = null;
		}
		
		private void attach_Calentamientos(Calentamientos entity)
		{
			this.SendPropertyChanging();
			entity.Personal = this;
		}
		
		private void detach_Calentamientos(Calentamientos entity)
		{
			this.SendPropertyChanging();
			entity.Personal = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Productos")]
	public partial class Productos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private System.Nullable<decimal> _Precio;
		
		private EntitySet<Registro_Productos> _Registro_Productos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnPrecioChanging(System.Nullable<decimal> value);
    partial void OnPrecioChanged();
    #endregion
		
		public Productos()
		{
			this._Registro_Productos = new EntitySet<Registro_Productos>(new Action<Registro_Productos>(this.attach_Registro_Productos), new Action<Registro_Productos>(this.detach_Registro_Productos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Money")]
		public System.Nullable<decimal> Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Productos_Registro_Productos", Storage="_Registro_Productos", ThisKey="Id", OtherKey="Id_Producto")]
		public EntitySet<Registro_Productos> Registro_Productos
		{
			get
			{
				return this._Registro_Productos;
			}
			set
			{
				this._Registro_Productos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Registro_Productos(Registro_Productos entity)
		{
			this.SendPropertyChanging();
			entity.Productos = this;
		}
		
		private void detach_Registro_Productos(Registro_Productos entity)
		{
			this.SendPropertyChanging();
			entity.Productos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Programas")]
	public partial class Programas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Descripcion;
		
		private System.Nullable<decimal> _Precio_Inscripcion;
		
		private System.Nullable<decimal> _Precio_periodo;
		
		private string _Status;
		
		private EntitySet<Cliente_Programa> _Cliente_Programa;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnPrecio_InscripcionChanging(System.Nullable<decimal> value);
    partial void OnPrecio_InscripcionChanged();
    partial void OnPrecio_periodoChanging(System.Nullable<decimal> value);
    partial void OnPrecio_periodoChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public Programas()
		{
			this._Cliente_Programa = new EntitySet<Cliente_Programa>(new Action<Cliente_Programa>(this.attach_Cliente_Programa), new Action<Cliente_Programa>(this.detach_Cliente_Programa));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio_Inscripcion", DbType="Money")]
		public System.Nullable<decimal> Precio_Inscripcion
		{
			get
			{
				return this._Precio_Inscripcion;
			}
			set
			{
				if ((this._Precio_Inscripcion != value))
				{
					this.OnPrecio_InscripcionChanging(value);
					this.SendPropertyChanging();
					this._Precio_Inscripcion = value;
					this.SendPropertyChanged("Precio_Inscripcion");
					this.OnPrecio_InscripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio_periodo", DbType="Money")]
		public System.Nullable<decimal> Precio_periodo
		{
			get
			{
				return this._Precio_periodo;
			}
			set
			{
				if ((this._Precio_periodo != value))
				{
					this.OnPrecio_periodoChanging(value);
					this.SendPropertyChanging();
					this._Precio_periodo = value;
					this.SendPropertyChanged("Precio_periodo");
					this.OnPrecio_periodoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(4000) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Programas_Cliente_Programa", Storage="_Cliente_Programa", ThisKey="Id", OtherKey="ID_Programa")]
		public EntitySet<Cliente_Programa> Cliente_Programa
		{
			get
			{
				return this._Cliente_Programa;
			}
			set
			{
				this._Cliente_Programa.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cliente_Programa(Cliente_Programa entity)
		{
			this.SendPropertyChanging();
			entity.Programas = this;
		}
		
		private void detach_Cliente_Programa(Cliente_Programa entity)
		{
			this.SendPropertyChanging();
			entity.Programas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Registro_Productos")]
	public partial class Registro_Productos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdRegistro;
		
		private System.Nullable<int> _Id_Producto;
		
		private System.Nullable<int> _Cantidad_Vendida;
		
		private System.Nullable<System.DateTime> _FechaYHora;
		
		private int _Empleado_Turno;
		
		private EntityRef<Personal> _Personal;
		
		private EntityRef<Productos> _Productos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdRegistroChanging(int value);
    partial void OnIdRegistroChanged();
    partial void OnId_ProductoChanging(System.Nullable<int> value);
    partial void OnId_ProductoChanged();
    partial void OnCantidad_VendidaChanging(System.Nullable<int> value);
    partial void OnCantidad_VendidaChanged();
    partial void OnFechaYHoraChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaYHoraChanged();
    partial void OnEmpleado_TurnoChanging(int value);
    partial void OnEmpleado_TurnoChanged();
    #endregion
		
		public Registro_Productos()
		{
			this._Personal = default(EntityRef<Personal>);
			this._Productos = default(EntityRef<Productos>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRegistro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdRegistro
		{
			get
			{
				return this._IdRegistro;
			}
			set
			{
				if ((this._IdRegistro != value))
				{
					this.OnIdRegistroChanging(value);
					this.SendPropertyChanging();
					this._IdRegistro = value;
					this.SendPropertyChanged("IdRegistro");
					this.OnIdRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Producto", DbType="Int")]
		public System.Nullable<int> Id_Producto
		{
			get
			{
				return this._Id_Producto;
			}
			set
			{
				if ((this._Id_Producto != value))
				{
					if (this._Productos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_ProductoChanging(value);
					this.SendPropertyChanging();
					this._Id_Producto = value;
					this.SendPropertyChanged("Id_Producto");
					this.OnId_ProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad_Vendida", DbType="Int")]
		public System.Nullable<int> Cantidad_Vendida
		{
			get
			{
				return this._Cantidad_Vendida;
			}
			set
			{
				if ((this._Cantidad_Vendida != value))
				{
					this.OnCantidad_VendidaChanging(value);
					this.SendPropertyChanging();
					this._Cantidad_Vendida = value;
					this.SendPropertyChanged("Cantidad_Vendida");
					this.OnCantidad_VendidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaYHora", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaYHora
		{
			get
			{
				return this._FechaYHora;
			}
			set
			{
				if ((this._FechaYHora != value))
				{
					this.OnFechaYHoraChanging(value);
					this.SendPropertyChanging();
					this._FechaYHora = value;
					this.SendPropertyChanged("FechaYHora");
					this.OnFechaYHoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empleado_Turno", DbType="Int NOT NULL")]
		public int Empleado_Turno
		{
			get
			{
				return this._Empleado_Turno;
			}
			set
			{
				if ((this._Empleado_Turno != value))
				{
					if (this._Personal.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmpleado_TurnoChanging(value);
					this.SendPropertyChanging();
					this._Empleado_Turno = value;
					this.SendPropertyChanged("Empleado_Turno");
					this.OnEmpleado_TurnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personal_Registro_Productos", Storage="_Personal", ThisKey="Empleado_Turno", OtherKey="Id", IsForeignKey=true)]
		public Personal Personal
		{
			get
			{
				return this._Personal.Entity;
			}
			set
			{
				Personal previousValue = this._Personal.Entity;
				if (((previousValue != value) 
							|| (this._Personal.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Personal.Entity = null;
						previousValue.Registro_Productos.Remove(this);
					}
					this._Personal.Entity = value;
					if ((value != null))
					{
						value.Registro_Productos.Add(this);
						this._Empleado_Turno = value.Id;
					}
					else
					{
						this._Empleado_Turno = default(int);
					}
					this.SendPropertyChanged("Personal");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Productos_Registro_Productos", Storage="_Productos", ThisKey="Id_Producto", OtherKey="Id", IsForeignKey=true)]
		public Productos Productos
		{
			get
			{
				return this._Productos.Entity;
			}
			set
			{
				Productos previousValue = this._Productos.Entity;
				if (((previousValue != value) 
							|| (this._Productos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Productos.Entity = null;
						previousValue.Registro_Productos.Remove(this);
					}
					this._Productos.Entity = value;
					if ((value != null))
					{
						value.Registro_Productos.Add(this);
						this._Id_Producto = value.Id;
					}
					else
					{
						this._Id_Producto = default(Nullable<int>);
					}
					this.SendPropertyChanged("Productos");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Seguimiento")]
	public partial class Seguimiento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.DateTime _Fecha;
		
		private decimal _Peso;
		
		private decimal _Caja_Toraxica;
		
		private decimal _Cintura;
		
		private decimal _Abdomen;
		
		private decimal _Cadera;
		
		private decimal _Muslo;
		
		private decimal _Gastronmio;
		
		private decimal _Biceps;
		
		private decimal _Flexibilidad;
		
		private decimal _Saldo_Mes;
		
		private int _Cliente_ID;
		
		private int _Personal_ID;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Personal> _Personal;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnPesoChanging(decimal value);
    partial void OnPesoChanged();
    partial void OnCaja_ToraxicaChanging(decimal value);
    partial void OnCaja_ToraxicaChanged();
    partial void OnCinturaChanging(decimal value);
    partial void OnCinturaChanged();
    partial void OnAbdomenChanging(decimal value);
    partial void OnAbdomenChanged();
    partial void OnCaderaChanging(decimal value);
    partial void OnCaderaChanged();
    partial void OnMusloChanging(decimal value);
    partial void OnMusloChanged();
    partial void OnGastronmioChanging(decimal value);
    partial void OnGastronmioChanged();
    partial void OnBicepsChanging(decimal value);
    partial void OnBicepsChanged();
    partial void OnFlexibilidadChanging(decimal value);
    partial void OnFlexibilidadChanged();
    partial void OnSaldo_MesChanging(decimal value);
    partial void OnSaldo_MesChanged();
    partial void OnCliente_IDChanging(int value);
    partial void OnCliente_IDChanged();
    partial void OnPersonal_IDChanging(int value);
    partial void OnPersonal_IDChanged();
    #endregion
		
		public Seguimiento()
		{
			this._Cliente = default(EntityRef<Cliente>);
			this._Personal = default(EntityRef<Personal>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Peso", DbType="Decimal(18,0) NOT NULL")]
		public decimal Peso
		{
			get
			{
				return this._Peso;
			}
			set
			{
				if ((this._Peso != value))
				{
					this.OnPesoChanging(value);
					this.SendPropertyChanging();
					this._Peso = value;
					this.SendPropertyChanged("Peso");
					this.OnPesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caja_Toraxica", DbType="Decimal(18,0) NOT NULL")]
		public decimal Caja_Toraxica
		{
			get
			{
				return this._Caja_Toraxica;
			}
			set
			{
				if ((this._Caja_Toraxica != value))
				{
					this.OnCaja_ToraxicaChanging(value);
					this.SendPropertyChanging();
					this._Caja_Toraxica = value;
					this.SendPropertyChanged("Caja_Toraxica");
					this.OnCaja_ToraxicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cintura", DbType="Decimal(18,0) NOT NULL")]
		public decimal Cintura
		{
			get
			{
				return this._Cintura;
			}
			set
			{
				if ((this._Cintura != value))
				{
					this.OnCinturaChanging(value);
					this.SendPropertyChanging();
					this._Cintura = value;
					this.SendPropertyChanged("Cintura");
					this.OnCinturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abdomen", DbType="Decimal(18,0) NOT NULL")]
		public decimal Abdomen
		{
			get
			{
				return this._Abdomen;
			}
			set
			{
				if ((this._Abdomen != value))
				{
					this.OnAbdomenChanging(value);
					this.SendPropertyChanging();
					this._Abdomen = value;
					this.SendPropertyChanged("Abdomen");
					this.OnAbdomenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cadera", DbType="Decimal(18,0) NOT NULL")]
		public decimal Cadera
		{
			get
			{
				return this._Cadera;
			}
			set
			{
				if ((this._Cadera != value))
				{
					this.OnCaderaChanging(value);
					this.SendPropertyChanging();
					this._Cadera = value;
					this.SendPropertyChanged("Cadera");
					this.OnCaderaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Muslo", DbType="Decimal(18,0) NOT NULL")]
		public decimal Muslo
		{
			get
			{
				return this._Muslo;
			}
			set
			{
				if ((this._Muslo != value))
				{
					this.OnMusloChanging(value);
					this.SendPropertyChanging();
					this._Muslo = value;
					this.SendPropertyChanged("Muslo");
					this.OnMusloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gastronmio", DbType="Decimal(18,0) NOT NULL")]
		public decimal Gastronmio
		{
			get
			{
				return this._Gastronmio;
			}
			set
			{
				if ((this._Gastronmio != value))
				{
					this.OnGastronmioChanging(value);
					this.SendPropertyChanging();
					this._Gastronmio = value;
					this.SendPropertyChanged("Gastronmio");
					this.OnGastronmioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Biceps", DbType="Decimal(18,0) NOT NULL")]
		public decimal Biceps
		{
			get
			{
				return this._Biceps;
			}
			set
			{
				if ((this._Biceps != value))
				{
					this.OnBicepsChanging(value);
					this.SendPropertyChanging();
					this._Biceps = value;
					this.SendPropertyChanged("Biceps");
					this.OnBicepsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flexibilidad", DbType="Decimal(18,0) NOT NULL")]
		public decimal Flexibilidad
		{
			get
			{
				return this._Flexibilidad;
			}
			set
			{
				if ((this._Flexibilidad != value))
				{
					this.OnFlexibilidadChanging(value);
					this.SendPropertyChanging();
					this._Flexibilidad = value;
					this.SendPropertyChanged("Flexibilidad");
					this.OnFlexibilidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saldo_Mes", DbType="Money NOT NULL")]
		public decimal Saldo_Mes
		{
			get
			{
				return this._Saldo_Mes;
			}
			set
			{
				if ((this._Saldo_Mes != value))
				{
					this.OnSaldo_MesChanging(value);
					this.SendPropertyChanging();
					this._Saldo_Mes = value;
					this.SendPropertyChanged("Saldo_Mes");
					this.OnSaldo_MesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente_ID", DbType="Int NOT NULL")]
		public int Cliente_ID
		{
			get
			{
				return this._Cliente_ID;
			}
			set
			{
				if ((this._Cliente_ID != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCliente_IDChanging(value);
					this.SendPropertyChanging();
					this._Cliente_ID = value;
					this.SendPropertyChanged("Cliente_ID");
					this.OnCliente_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Personal_ID", DbType="Int NOT NULL")]
		public int Personal_ID
		{
			get
			{
				return this._Personal_ID;
			}
			set
			{
				if ((this._Personal_ID != value))
				{
					if (this._Personal.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPersonal_IDChanging(value);
					this.SendPropertyChanging();
					this._Personal_ID = value;
					this.SendPropertyChanged("Personal_ID");
					this.OnPersonal_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Seguimiento", Storage="_Cliente", ThisKey="Cliente_ID", OtherKey="Id", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Seguimiento.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Seguimiento.Add(this);
						this._Cliente_ID = value.Id;
					}
					else
					{
						this._Cliente_ID = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personal_Seguimiento", Storage="_Personal", ThisKey="Personal_ID", OtherKey="Id", IsForeignKey=true)]
		public Personal Personal
		{
			get
			{
				return this._Personal.Entity;
			}
			set
			{
				Personal previousValue = this._Personal.Entity;
				if (((previousValue != value) 
							|| (this._Personal.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Personal.Entity = null;
						previousValue.Seguimiento.Remove(this);
					}
					this._Personal.Entity = value;
					if ((value != null))
					{
						value.Seguimiento.Add(this);
						this._Personal_ID = value.Id;
					}
					else
					{
						this._Personal_ID = default(int);
					}
					this.SendPropertyChanged("Personal");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Calentamientos")]
	public partial class Calentamientos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Num_registro;
		
		private System.Nullable<System.DateTime> _FechaYHora;
		
		private System.Nullable<decimal> _Cantidad;
		
		private int _EmpleadoDeTurno;
		
		private decimal _Cuota;
		
		private EntityRef<Personal> _Personal;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNum_registroChanging(int value);
    partial void OnNum_registroChanged();
    partial void OnFechaYHoraChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaYHoraChanged();
    partial void OnCantidadChanging(System.Nullable<decimal> value);
    partial void OnCantidadChanged();
    partial void OnEmpleadoDeTurnoChanging(int value);
    partial void OnEmpleadoDeTurnoChanged();
    partial void OnCuotaChanging(decimal value);
    partial void OnCuotaChanged();
    #endregion
		
		public Calentamientos()
		{
			this._Personal = default(EntityRef<Personal>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_registro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Num_registro
		{
			get
			{
				return this._Num_registro;
			}
			set
			{
				if ((this._Num_registro != value))
				{
					this.OnNum_registroChanging(value);
					this.SendPropertyChanging();
					this._Num_registro = value;
					this.SendPropertyChanged("Num_registro");
					this.OnNum_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaYHora", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaYHora
		{
			get
			{
				return this._FechaYHora;
			}
			set
			{
				if ((this._FechaYHora != value))
				{
					this.OnFechaYHoraChanging(value);
					this.SendPropertyChanging();
					this._FechaYHora = value;
					this.SendPropertyChanged("FechaYHora");
					this.OnFechaYHoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Money")]
		public System.Nullable<decimal> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpleadoDeTurno", DbType="Int NOT NULL")]
		public int EmpleadoDeTurno
		{
			get
			{
				return this._EmpleadoDeTurno;
			}
			set
			{
				if ((this._EmpleadoDeTurno != value))
				{
					if (this._Personal.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmpleadoDeTurnoChanging(value);
					this.SendPropertyChanging();
					this._EmpleadoDeTurno = value;
					this.SendPropertyChanged("EmpleadoDeTurno");
					this.OnEmpleadoDeTurnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cuota", DbType="Money NOT NULL")]
		public decimal Cuota
		{
			get
			{
				return this._Cuota;
			}
			set
			{
				if ((this._Cuota != value))
				{
					this.OnCuotaChanging(value);
					this.SendPropertyChanging();
					this._Cuota = value;
					this.SendPropertyChanged("Cuota");
					this.OnCuotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personal_Calentamientos", Storage="_Personal", ThisKey="EmpleadoDeTurno", OtherKey="Id", IsForeignKey=true)]
		public Personal Personal
		{
			get
			{
				return this._Personal.Entity;
			}
			set
			{
				Personal previousValue = this._Personal.Entity;
				if (((previousValue != value) 
							|| (this._Personal.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Personal.Entity = null;
						previousValue.Calentamientos.Remove(this);
					}
					this._Personal.Entity = value;
					if ((value != null))
					{
						value.Calentamientos.Add(this);
						this._EmpleadoDeTurno = value.Id;
					}
					else
					{
						this._EmpleadoDeTurno = default(int);
					}
					this.SendPropertyChanged("Personal");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gastos")]
	public partial class Gastos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Descripcion;
		
		private decimal _Monto;
		
		private System.DateTime _Fecha;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnMontoChanging(decimal value);
    partial void OnMontoChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    #endregion
		
		public Gastos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Money NOT NULL")]
		public decimal Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this.OnMontoChanging(value);
					this.SendPropertyChanging();
					this._Monto = value;
					this.SendPropertyChanged("Monto");
					this.OnMontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
